version: "1.0"
services:
    db:
        image: postgres
        env_file:
            - env/.env.docker
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
