# Generated by Django 4.2.13 on 2024-06-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="n4_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="str_name", max_length=50, null=True
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, db_column="str_host", max_length=50, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, db_column="str_type", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "league",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="n4_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True, db_column="str_name", max_length=50, null=True
                    ),
                ),
                (
                    "team_acronym_name",
                    models.CharField(
                        blank=True,
                        db_column="str_acronym_name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "team_logo_link",
                    models.CharField(
                        blank=True, db_column="str_logo_link", max_length=100, null=True
                    ),
                ),
                (
                    "team_location",
                    models.CharField(
                        blank=True, db_column="str_location", max_length=32, null=True
                    ),
                ),
            ],
            options={
                "db_table": "team",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TeamAttendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="n4_id", primary_key=True, serialize=False
                    ),
                ),
                ("play", models.SmallIntegerField(db_column="n4_play")),
                ("win", models.SmallIntegerField(db_column="n4_win")),
                ("draw", models.SmallIntegerField(db_column="n4_draw")),
                ("lost", models.SmallIntegerField(db_column="n4_lost")),
                ("score", models.SmallIntegerField(db_column="n4_score")),
                ("conceded", models.SmallIntegerField(db_column="n4_conceded")),
                ("banned", models.SmallIntegerField(db_column="n4_banned")),
                ("season", models.SmallIntegerField(db_column="n4_season")),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        db_column="n4_league_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Team.league",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        db_column="n4_team_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Team.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_attendance",
                "managed": True,
            },
        ),
    ]
