# Generated by Django 3.1.6 on 2024-07-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_acronym_name',
            new_name='acronym_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_logo_link',
            new_name='logo_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
    ]
