# Generated by Django 4.2.13 on 2024-07-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Team", "0003_league_acronym_name_league_logo_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="logo_link",
            field=models.CharField(
                blank=True, db_column="str_logo_link", max_length=200, null=True
            ),
        ),
    ]
