# Generated by Django 4.2.13 on 2024-07-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Team", "0004_alter_league_logo_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamattendance",
            name="banned",
            field=models.SmallIntegerField(db_column="n4_banned", default=0),
        ),
        migrations.AlterField(
            model_name="teamattendance",
            name="conceded",
            field=models.SmallIntegerField(db_column="n4_conceded", default=0),
        ),
        migrations.AlterField(
            model_name="teamattendance",
            name="draw",
            field=models.SmallIntegerField(db_column="n4_draw", default=0),
        ),
        migrations.AlterField(
            model_name="teamattendance",
            name="lost",
            field=models.SmallIntegerField(db_column="n4_lost", default=0),
        ),
        migrations.AlterField(
            model_name="teamattendance",
            name="play",
            field=models.SmallIntegerField(db_column="n4_play", default=0),
        ),
        migrations.AlterField(
            model_name="teamattendance",
            name="score",
            field=models.SmallIntegerField(db_column="n4_score", default=0),
        ),
        migrations.AlterField(
            model_name="teamattendance",
            name="season",
            field=models.SmallIntegerField(db_column="n4_season", default=0),
        ),
        migrations.AlterField(
            model_name="teamattendance",
            name="win",
            field=models.SmallIntegerField(db_column="n4_win", default=0),
        ),
    ]
