# Generated by Django 4.2.13 on 2024-07-24 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Player", "0001_initial"),
        ("Team", "0004_alter_league_logo_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitedMatch",
            fields=[
                (
                    "match_id",
                    models.AutoField(
                        db_column="n4_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "match_stadium",
                    models.CharField(db_column="str_name", max_length=50),
                ),
                ("match_home", models.BooleanField()),
                ("match_home_score", models.IntegerField(blank=True, null=True)),
                ("match_enemy_score", models.IntegerField(blank=True, null=True)),
                ("match_date", models.DateField(blank=True, null=True)),
                ("match_lineup", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "match_referee",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("match_type", models.TextField(blank=True, null=True)),
                (
                    "match_enemy",
                    models.ForeignKey(
                        db_column="n4_enemy_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Team.teamattendance",
                    ),
                ),
            ],
            options={
                "db_table": "united_match",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UnitedMatchEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="n4_id", primary_key=True, serialize=False
                    ),
                ),
                ("minute", models.IntegerField(db_column="n4_minute")),
                (
                    "part",
                    models.TextField(
                        choices=[
                            ("FIRST_LEG", "FIRST_LEG"),
                            ("SECOND_LEG", "SECOND_LEG"),
                            ("SUB_FIRST", "SUB_FIRST"),
                            ("SUB_SECOND", "SUB_SECOND"),
                            ("PENALTY", "PENALTY"),
                            ("SUBSTITUTE_IN", "SUBSTITUTE_IN"),
                        ],
                        db_column="str_half",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("RED_CARD", "RED_CARD"),
                            ("YELLOW_CARD", "YELLOW_CARD"),
                            ("GOAL", "GOAL"),
                            ("OWN_GOAL", "OWN_GOAL"),
                            ("SUBSTITUTE_OUT", "SUBSTITUTE_OUT"),
                            ("OUT_OF_TIME", "OUT_OF_TIME"),
                        ],
                        db_column="str_type",
                        null=True,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        db_column="n4_match_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UnitedMatch.unitedmatch",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        db_column="n4_player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Player.player",
                    ),
                ),
            ],
            options={
                "db_table": "united_match_event",
                "managed": True,
            },
        ),
    ]
