# Generated by Django 4.2.13 on 2024-07-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="n4_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="str_name", max_length=50)),
                (
                    "full_name",
                    models.CharField(db_column="str_full_name", max_length=50),
                ),
                (
                    "avatar_link",
                    models.CharField(db_column="str_avatar_link", max_length=150),
                ),
                (
                    "nationality",
                    models.CharField(db_column="str_nationality", max_length=30),
                ),
                ("birthday", models.DateField(db_column="dt_birthday")),
                ("right_foot", models.BooleanField(db_column="is_right_foot")),
                ("kit_number", models.IntegerField(db_column="n4_kit_number")),
                ("height", models.IntegerField(db_column="n4_height")),
                (
                    "role",
                    models.TextField(
                        choices=[
                            ("GOALKEEPER", "GOALKEEPERS"),
                            ("DEFENDER", "DEFENDER"),
                            ("MIDFIELDER", "MIDFIELDER"),
                            ("FORWARD", "FORWARD"),
                        ],
                        db_column="str_role",
                        null=True,
                    ),
                ),
                (
                    "salary",
                    models.IntegerField(blank=True, db_column="n4_salary", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("LOAN", "LOAN"),
                            ("LEFT", "LEFT"),
                        ],
                        db_column="str_status",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "player",
                "ordering": ["birthday"],
                "managed": True,
            },
        ),
    ]
