create table match
(
    n4_id          integer generated by default as identity
        primary key,
    n4_round       integer not null,
    n4_fthg        integer not null,
    n4_ftag        integer not null,
    str_date       varchar(50),
    n4_external_id integer,
    n4_away_id     integer not null
        constraint match_n4_away_id_81710dc3_fk_team_attendance_n4_id
            references team_attendance
            deferrable initially deferred,
    n4_home_id     integer not null
        constraint match_n4_home_id_b75e7e5c_fk_team_attendance_n4_id
            references team_attendance
            deferrable initially deferred,
    n4_league_id   integer not null
        constraint match_n4_league_id_7a961dec_fk_league_n4_id
            references league
            deferrable initially deferred
);

alter table match
    owner to pldjango;

create index match_n4_away_id_81710dc3
    on match (n4_away_id);

create index match_n4_home_id_b75e7e5c
    on match (n4_home_id);

create index match_n4_league_id_7a961dec
    on match (n4_league_id);

INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (1, 1, 0, null, 93330, 420, 354, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (1, 1, 1, null, 93329, 329, 278, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (1, 2, 2, null, 93328, 394, 244, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (1, 5, 1, null, 93326, 235, 363, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (1, 1, 1, null, 93323, 411, 253, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (1, 4, 1, null, 93324, 338, 261, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (1, 0, 1, null, 93325, 305, 296, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (1, 0, 1, null, 93327, 287, 429, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (1, 2, 1, null, 93322, 379, 226, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (1, 0, 3, null, 93321, 345, 270, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (2, 0, 1, null, 93332, 226, 287, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (2, 3, 1, null, 93339, 278, 411, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (2, 4, 0, null, 93331, 296, 235, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (2, 1, 0, null, 93336, 363, 345, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (2, 2, 0, null, 93338, 354, 394, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (2, 0, 3, null, 93333, 244, 305, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (2, 3, 1, null, 93334, 253, 329, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (2, 1, 4, null, 93340, 261, 420, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (2, 2, 1, null, 93337, 429, 379, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (3, 1, 2, null, 93349, 329, 363, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (3, 1, 3, null, 93345, 235, 270, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (3, 1, 2, null, 93350, 345, 429, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (3, 1, 3, null, 93344, 411, 261, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (3, 2, 2, null, 93341, 305, 226, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (3, 1, 1, null, 93343, 287, 244, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (3, 0, 1, null, 93347, 420, 296, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (3, 3, 2, null, 93348, 379, 354, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (3, 0, 2, null, 93342, 394, 253, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (3, 3, 0, null, 93346, 338, 278, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (4, 3, 1, null, 93351, 354, 226, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (4, 3, 2, null, 93356, 420, 287, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (4, 3, 0, null, 93357, 235, 329, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (4, 3, 1, null, 93353, 363, 261, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (4, 2, 2, null, 93352, 253, 244, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (4, 2, 5, null, 93354, 394, 270, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (4, 0, 1, null, 93355, 379, 278, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (4, 5, 1, null, 93359, 305, 345, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (4, 2, 2, null, 93360, 296, 429, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (4, 1, 2, null, 93358, 411, 338, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (5, 1, 1, null, 93367, 270, 379, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (5, 0, 1, null, 93363, 226, 296, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (5, 0, 0, null, 93362, 278, 253, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (5, 1, 0, null, 93366, 244, 363, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (5, 3, 1, null, 93361, 287, 235, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (5, 1, 0, null, 93364, 338, 305, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (5, 1, 3, null, 93365, 261, 354, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (5, 2, 1, null, 93368, 429, 394, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (5, 1, 3, null, 93369, 345, 411, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (5, 1, 3, null, 93370, 329, 420, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (6, 0, 8, null, 93380, 363, 429, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (6, 2, 2, null, 93371, 394, 226, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (6, 3, 1, null, 93373, 253, 261, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (6, 0, 1, null, 93375, 235, 278, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (6, 3, 1, null, 93377, 411, 329, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (6, 0, 1, null, 93374, 354, 270, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (6, 1, 3, null, 93372, 296, 244, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (6, 0, 0, null, 93376, 305, 287, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (6, 1, 1, null, 93378, 420, 338, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (6, 2, 0, null, 93379, 379, 345, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (7, 1, 2, null, 93335, 270, 338, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (7, 0, 2, null, 93384, 278, 305, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (7, 1, 1, null, 93387, 244, 379, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (7, 2, 1, null, 93388, 329, 394, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (7, 0, 4, null, 93382, 226, 253, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (7, 1, 2, null, 93383, 338, 296, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (7, 0, 1, null, 93385, 287, 354, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (7, 2, 0, null, 93386, 270, 363, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (7, 2, 0, null, 93389, 429, 411, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (7, 2, 1, null, 93390, 345, 420, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (7, 6, 1, null, 93381, 261, 235, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (8, 1, 0, null, 93391, 345, 226, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (8, 2, 2, null, 93392, 329, 261, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (8, 2, 2, null, 93399, 363, 411, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (8, 1, 1, null, 93400, 235, 420, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (8, 0, 0, null, 93394, 379, 287, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (8, 1, 4, null, 93393, 278, 270, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (8, 3, 0, null, 93395, 253, 296, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (8, 3, 1, null, 93396, 429, 305, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (8, 2, 1, null, 93398, 244, 354, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (8, 0, 1, null, 93397, 394, 338, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (9, 2, 0, null, 93410, 305, 394, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (9, 4, 1, null, 93401, 411, 235, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (9, 1, 2, null, 93409, 354, 429, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (9, 2, 2, null, 93404, 226, 278, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (9, 1, 2, null, 93402, 420, 253, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (9, 3, 0, null, 93403, 270, 244, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (9, 2, 1, null, 93406, 261, 345, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (9, 4, 0, null, 93407, 287, 363, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (9, 2, 2, null, 93408, 338, 379, 1);
INSERT INTO public.match (n4_round, n4_fthg, n4_ftag, str_date, n4_external_id, n4_away_id, n4_home_id, n4_league_id) VALUES (9, 2, 0, null, 93405, 296, 329, 1);
