create table team
(
    n4_id            integer generated by default as identity
        primary key,
    str_name         varchar(50),
    str_acronym_name varchar(50),
    str_logo_link    varchar(100),
    str_location     varchar(32)
);

alter table team
    owner to pldjango;

create unique index idx_team_unique
    on team (str_name);

INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Arsenal', 'ARS', 'https://resources.premierleague.com/premierleague/badges/t3.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Aston Villa', 'AVL', 'https://resources.premierleague.com/premierleague/badges/t7.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Brenford', 'BRE', 'https://resources.premierleague.com/premierleague/badges/t94.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('AFC Bournemouth', 'BOU', 'https://resources.premierleague.com/premierleague/badges/t91.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Brighton and Hove Albion', 'BHA', 'https://resources.premierleague.com/premierleague/badges/t36.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Burnley', 'BUR', 'https://resources.premierleague.com/premierleague/badges/t90.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Chelsea', 'CHE', 'https://resources.premierleague.com/premierleague/badges/t8.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Crystal Palace', 'CRY', 'https://resources.premierleague.com/premierleague/badges/t31.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Everton', 'EVE', 'https://resources.premierleague.com/premierleague/badges/t11.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Leeds United', 'LEE', 'https://resources.premierleague.com/premierleague/badges/t2.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Leicester City', 'LEI', 'https://resources.premierleague.com/premierleague/badges/t13.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Liverpool', 'LIV', 'https://resources.premierleague.com/premierleague/badges/t14.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Luton Town', 'LUT', 'https://resources.premierleague.com/premierleague/badges/t102.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Manchester City', 'MCI', 'https://resources.premierleague.com/premierleague/badges/t43.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Manchester United', 'MUN', 'https://resources.premierleague.com/premierleague/badges/t1.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Newcastle United', 'NEW', 'https://resources.premierleague.com/premierleague/badges/t4.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Norwich City', 'NOR', 'https://resources.premierleague.com/premierleague/badges/t45.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Southamton', 'SOU', 'https://resources.premierleague.com/premierleague/badges/t20.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Tottenham Hotspur', 'TOT', 'https://resources.premierleague.com/premierleague/badges/t6.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Watford', 'WAT', 'https://resources.premierleague.com/premierleague/badges/t57.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('West Ham United', 'WHU', 'https://resources.premierleague.com/premierleague/badges/t21.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Wolverhamton Wanderers', 'WOL', 'https://resources.premierleague.com/premierleague/badges/t39.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Sheffield United', 'SHU', 'https://resources.premierleague.com/premierleague/badges/t49.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Fulham', 'FUL', 'https://resources.premierleague.com/premierleague/badges/t54.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Bolton Wanderers', 'BOL', 'https://resources.premierleague.com/premierleague/badges/t30.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('West Bromwich Albion', 'WBA', 'https://resources.premierleague.com/premierleague/badges/t35.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Huddersfield Town', 'HUD', 'https://resources.premierleague.com/premierleague/badges/t38.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Charlton Athletic', 'CHA', 'https://resources.premierleague.com/premierleague/badges/t33.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Birmingham City', 'BIR', 'https://resources.premierleague.com/premierleague/badges/t41.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Portsmouth FC', 'POR', 'https://resources.premierleague.com/premierleague/badges/t47.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Queens Park Rangers', 'QPR', 'https://resources.premierleague.com/premierleague/badges/t52.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Blackpool', 'BLP', 'https://resources.premierleague.com/premierleague/badges/t92.png', 'England');
INSERT INTO public.team (str_name, str_acronym_name, str_logo_link, str_location) VALUES ('Nottingham Forest', 'NFO', 'https://resources.premierleague.com/premierleague/badges/t17.png', 'England');
