create table team_attendance
(
    n4_id        integer generated by default as identity
        primary key,
    n4_play      smallint not null,
    n4_win       smallint not null,
    n4_draw      smallint not null,
    n4_lost      smallint not null,
    n4_score     smallint not null,
    n4_conceded  smallint not null,
    n4_banned    smallint not null,
    n4_season    smallint not null,
    n4_league_id integer
        constraint team_attendance_n4_league_id_af4d95e7_fk_league_n4_id
            references league
            deferrable initially deferred,
    n4_team_id   integer
        constraint team_attendance_n4_team_id_f0fd75d9_fk_team_n4_id
            references team
            deferrable initially deferred
);

alter table team_attendance
    owner to pldjango;

create index team_attendance_n4_league_id_af4d95e7
    on team_attendance (n4_league_id);

create index team_attendance_n4_team_id_f0fd75d9
    on team_attendance (n4_team_id);

create unique index idx_team_attendance_unique
    on team_attendance (n4_team_id, n4_league_id, n4_season);

INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 1);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 1);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 1);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 1);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 1);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 1);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 1);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 1);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 2);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 2);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 2);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 2);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 2);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 2);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 2);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 2);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 3);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 3);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 3);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 3);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 3);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 3);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 3);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 3);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 4);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 4);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 4);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 4);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 4);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 4);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 4);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 5);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 5);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 5);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 5);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 5);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 5);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 5);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 5);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 6);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 6);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 6);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 6);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 6);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 6);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 6);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 7);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 7);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 7);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 7);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 7);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 7);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 7);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 7);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 8);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 8);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 8);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 8);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 8);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 8);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 8);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 8);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 9);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 9);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 9);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 9);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 9);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 9);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 9);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 9);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 10);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 10);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 10);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 10);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 10);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 10);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 10);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 11);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 11);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 11);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 11);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 11);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 11);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 11);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 11);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 12);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 12);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 12);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 12);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 12);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 12);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 12);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 12);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 13);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 13);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 13);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 13);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 13);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 13);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 13);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 13);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 14);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 14);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 14);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 14);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 14);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 14);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 15);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 15);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 15);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 15);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 15);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 15);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 15);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 15);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 16);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 16);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 16);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 16);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 16);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 16);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 16);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 16);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 17);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 17);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 17);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 17);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 17);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 17);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 17);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 17);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 18);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 18);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 18);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 18);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 18);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 18);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 18);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 19);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 19);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 19);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 19);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 19);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 19);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 20);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 20);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 20);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 20);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 20);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 20);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 20);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 20);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 21);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 21);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 21);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 21);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 21);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 21);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 21);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 21);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 22);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 22);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 22);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 22);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 22);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 22);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 22);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 22);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 23);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 23);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 23);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 23);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 23);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 23);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 23);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 23);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 24);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 24);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 1, 24);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 24);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 24);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 1, 24);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 24);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 24);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 2, 25);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2024, 3, 25);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 2, 25);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2023, 3, 25);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 2, 25);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (0, 0, 0, 0, 0, 0, 0, 2022, 3, 25);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 2, 0, 0, 3, 0, 0, 2024, 1, 21);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 1, 0, 1, 3, 3, 0, 2024, 1, 10);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 1, 1, 0, 5, 2, 0, 2024, 1, 2);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 0, 1, 1, 3, 6, 0, 2024, 1, 23);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 0, 0, 2, 2, 5, 0, 2024, 1, 25);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 2, 0, 0, 4, 2, 0, 2024, 1, 16);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 1, 1, 0, 6, 3, 0, 2024, 1, 7);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 1, 1, 0, 3, 2, 0, 2024, 1, 1);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 0, 0, 2, 1, 5, 0, 2024, 1, 4);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 1, 1, 0, 3, 2, 0, 2024, 1, 24);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 1, 0, 1, 4, 2, 0, 2024, 1, 3);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 0, 0, 2, 1, 7, 0, 2024, 1, 6);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 1, 0, 1, 2, 2, 0, 2024, 1, 15);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 0, 1, 1, 3, 4, 0, 2024, 1, 5);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 1, 1, 0, 6, 2, 0, 2024, 1, 17);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 0, 1, 1, 0, 4, 0, 2024, 1, 8);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 0, 2, 0, 2, 2, 0, 2024, 1, 19);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 0, 1, 1, 2, 3, 0, 2024, 1, 14);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 1, 1, 0, 4, 2, 0, 2024, 1, 13);
INSERT INTO public.team_attendance (n4_play, n4_win, n4_draw, n4_lost, n4_score, n4_conceded, n4_banned, n4_season, n4_league_id, n4_team_id) VALUES (2, 1, 0, 1, 3, 2, 0, 2024, 1, 9);
