# Generated by Django 3.1.6 on 2024-07-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Team', '0002_auto_20240721_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(db_column='n4_id', primary_key=True, serialize=False)),
                ('round', models.IntegerField(blank=True, db_column='n4_round')),
                ('fthg', models.IntegerField(blank=True, db_column='n4_fthg')),
                ('ftag', models.IntegerField(blank=True, db_column='n4_ftag')),
                ('refe', models.CharField(blank=True, max_length=50, null=True)),
                ('hsht', models.IntegerField(blank=True, db_column='n4_hsht', null=True)),
                ('asht', models.IntegerField(blank=True, db_column='n4_asht', null=True)),
                ('hsot', models.IntegerField(blank=True, db_column='n4_hsot', null=True)),
                ('asot', models.IntegerField(blank=True, db_column='n4_asot', null=True)),
                ('hcor', models.IntegerField(blank=True, db_column='n4_hcor', null=True)),
                ('acor', models.IntegerField(blank=True, db_column='n4_acor', null=True)),
                ('hfou', models.IntegerField(blank=True, db_column='n4_hfou', null=True)),
                ('afou', models.IntegerField(blank=True, db_column='n4_afou', null=True)),
                ('hyca', models.IntegerField(blank=True, db_column='n4_hyca', null=True)),
                ('ayca', models.IntegerField(blank=True, db_column='n4_ayca', null=True)),
                ('hrca', models.IntegerField(blank=True, db_column='n4_hrca', null=True)),
                ('arca', models.IntegerField(blank=True, db_column='n4_arca', null=True)),
                ('external_id', models.IntegerField(blank=True, db_column='n4_external_id', null=True)),
                ('away', models.ForeignKey(db_column='n4_away_id', on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='Team.teamattendance')),
                ('home', models.ForeignKey(db_column='n4_home_id', on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='Team.teamattendance')),
                ('league', models.ForeignKey(db_column='n4_league_id', on_delete=django.db.models.deletion.CASCADE, to='Team.league')),
            ],
            options={
                'db_table': 'match',
                'managed': True,
            },
        ),
    ]
