# Generated by Django 3.1.6 on 2023-03-08 08:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False, verbose_name='Player ID')),
                ('name', models.CharField(max_length=32)),
                ('fullname', models.CharField(max_length=64)),
                ('avatar_link', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(max_length=32)),
                ('birthdate', models.DateField()),
                ('right_foot', models.BooleanField(default=True)),
                ('kit_number', models.IntegerField()),
                ('height', models.IntegerField(default=150, verbose_name='player height (cm)')),
                ('position', models.CharField(choices=[('GOALKEEPERS', 'Goalkeepers'), ('DEFENDERS', 'Defenders'), ('MIDFIELDERS', 'Midfielders'), ('FORWARDS', 'Forwards')], max_length=11)),
                ('salary', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LEFT', 'Left'), ('LOAN', 'Loan')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False, verbose_name='Team ID')),
                ('name', models.CharField(max_length=32)),
                ('acronym_name', models.CharField(max_length=5)),
                ('logo_link', models.CharField(max_length=100)),
                ('association', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GroupStageTeam',
            fields=[
                ('group_team_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='Group Stage Team ID')),
                ('played_game', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('won_game', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('drawn_game', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('lost_game', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('goal_for', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('goal_against', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('goal_difference', models.IntegerField()),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('season', models.CharField(choices=[('EPL', 'Epl'), ('UCL', 'Ucl'), ('UEL', 'Uel'), ('FA', 'Fa'), ('EFL', 'Efl'), ('UECL', 'Uecl')], max_length=4)),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='United.team')),
            ],
        ),
    ]
