# Generated by Django 3.1.6 on 2023-03-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('United', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('account_email', models.CharField(max_length=256)),
                ('account_username', models.CharField(max_length=256)),
                ('account_phone', models.CharField(max_length=256)),
                ('account_name', models.CharField(max_length=256)),
                ('account_password', models.CharField(max_length=256)),
                ('account_role', models.TextField()),
                ('account_license_plate', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'tb_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_minute', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'r_goalscore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_stadium', models.CharField(max_length=256)),
                ('match_home', models.BooleanField()),
                ('match_home_score', models.IntegerField(blank=True, null=True)),
                ('match_enemy_score', models.IntegerField(blank=True, null=True)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('match_lineup', models.CharField(blank=True, max_length=5, null=True)),
                ('match_referee', models.CharField(blank=True, max_length=256, null=True)),
                ('match_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OwnGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_minute', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'r_owngoal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RedCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_minute', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'r_redcard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YellowCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yc_minute', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'r_yellowcard',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='groupstageteam',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False},
        ),
    ]
